apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::844085074134:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
        - system:masters
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::844085074134:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1KK354O3ELCAL
      username: system:node:{{EC2PrivateDNSName}}
  # mapRoles: |
  #   - groups:
  #     - system:masters
  #     rolearn: arn:aws:iam::844085074134:role/UdacityFlaskDeployCBKubectlRole
  #     username: build    
  #   - rolearn: arn:aws:iam::844085074134:role/UdacityFlaskDeployCBKubectlRole
  #     username: system:node:{{EC2PrivateDNSName}}
  #     groups:
  #       - system:bootstrappers
  #       - system:nodes
  mapUsers: |
    []
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"mapRoles":"- rolearn: arn:aws:iam::844085074134:role/UdacityFlaskDeployCBKubectlRole\n  username: system:node:{{EC2PrivateDNSName}}\n  groups:\n    - system:bootstrappers\n    - system:nodes\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"aws-auth","namespace":"kube-system"}}
  creationTimestamp: "2021-04-23T13:34:04Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapUsers: {}
    manager: eksctl.exe
    operation: Update
    time: "2021-04-23T13:34:04Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        f:mapRoles: {}
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2021-04-23T13:35:52Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1840"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 0736592f-1e3b-47d0-a2a9-c31f27a6e649
