apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::844085074134:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1N7Z4W4VRARMT
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::844085074134:role/UdacityFlaskDeployCBKubectlRole
      username: build
  # mapRoles: |
  #   - groups:
  #     - system:bootstrappers
  #     - system:nodes
  #     rolearn: arn:aws:iam::844085074134:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1N7Z4W4VRARMT
  #     username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-04-27T16:12:12Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
        f:mapUsers: {}
    manager: eksctl.exe
    operation: Update
    time: "2021-04-27T16:12:12Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1381"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: dd09c682-6412-427f-a316-a2e515b5473a
